### ISSUE TITLE
does someone succed in making this work?

### ISSUE THREAD

**Issue by gilcot** [dokufreaks/plugin-repo#4]
...because not working for me.

**Comment by turnermm** [comment]
This may address some of the problems:
https://github.com/turnermm/plugin-repo/archive/geshi_move.zip
It fixes only the fatal error which causes the crash and restores the highlighting. But it works only on a single file marked as a text file, which in github is the `raw` version.

**Comment by turnermm** [comment]
The repo plugin seems to be defunct, but the following version will give you useful access to github repositories: 
https://github.com/turnermm/repo_git/archive/master.zip

**Comment by gilcot** [comment]
Thanks @turnermm

**Comment by lpaulsen93** [comment]
The pull-request from @turnermm is merged now, closing this.
